---
abstract: 'Catmandu modules for working with MARC data'
author:
  - 'Patrick Hochstenbach, C<< <patrick.hochstenbach at ugent.be> >>'
build_requires:
  Module::Build: '0.3601'
  Test::More: '1.001003'
  Test::Simple: '1.001003'
  XML::XPath: '1.13'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catmandu-MARC
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Catmandu: '0.9103'
  JSON::XS: '2.3'
  MARC::File::MARCMaker: '0.05'
  MARC::File::MiJ: '0.04'
  MARC::File::XML: '0.93'
  MARC::Parser::RAW: '0.01'
  MARC::Record: v2.0.6
  Moo: '1.0'
  YAML::XS: '0.34'
  perl: v5.10.1
resources:
  bugtracker: https://github.com/LibreCat/Catmandu-MARC/issues
  homepage: https://github.com/LibreCat/Catmandu-MARC
  repository: https://github.com/LibreCat/Catmandu-MARC.git
version: '0.202'
x_contributors:
  - 'Chris Cormack <chrisc@catalyst.net.nz>'
  - 'Johann Rolschewski <rolschewski@gmail.com>'
  - 'Nicolas Steenlant <nicolas.steenlant@ugent.be>'
  - 'Robin Sheat <robin@catalyst.net.nz>'
