---
abstract: 'Catmandu modules for working with MARC data'
author:
  - 'Patrick Hochstenbach <patrick.hochstenbach@ugent.be>'
  - 'Nicolas Steenlant <nicolas.steenlant@ugent.be>'
build_requires:
  Software::License: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catmandu-MARC
provides:
  Catmandu::Exporter::MARC:
    file: lib/Catmandu/Exporter/MARC.pm
    version: 0
  Catmandu::Fix::marc_in_json:
    file: lib/Catmandu/Fix/marc_in_json.pm
    version: 0
  Catmandu::Fix::marc_map:
    file: lib/Catmandu/Fix/marc_map.pm
    version: 0
  Catmandu::Fix::marc_xml:
    file: lib/Catmandu/Fix/marc_xml.pm
    version: 0
  Catmandu::Importer::MARC:
    file: lib/Catmandu/Importer/MARC.pm
    version: 0
  Catmandu::MARC:
    file: lib/Catmandu/MARC.pm
    version: 0.0301
requires:
  Catmandu: 0.08
  MARC::File::XML: 0.93
  MARC::Record: 2.000003
  Moo: 1.0
  perl: v5.10.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.0301
